name: icevision
channels:
  - pytorch
  - fastai
  - defaults
dependencies:
  - pillow >9.0.0
  - python>3.6,<4
  - pytorch==1.10.2
  - torchvision==0.12.0
  - cudatoolkit=11.2
  - fastcore >=1.3.0,<1.4
  - fastai >=2.5.2
  - pip
  - pip:
      - icevision[all]==0.13
      - --find-links https://download.openmmlab.com/mmcv/dist/cu111/torch1.10.2/index.html
      - mmcv-full==1.3.17
      - mmdet
