name: icevision
channels:
  - pytorch
  - fastai
  - defaults
dependencies:
  - pillow >=9.0.0
  - python>3.6,<4
  - pytorch
  - torchvision
  - cudatoolkit=11.2
  - fastcore >=1.3.0,<1.4
  - fastai >=2.5.2
  - pip
  - pip:
      - icevision[all]==0.13
      - mmcv-full
      - mmdet
